# Usar una imagen base de Python
FROM python:3.8-slim-buster

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar los requerimientos del proyecto
COPY requirements.txt requirements.txt

# Instalar los requerimientos del proyecto
RUN pip install -r requirements.txt

# Copiar el resto del código del proyecto
COPY . .

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["python", "app.py"]
